let BANK=[];
const letters=['A','B','C','D'];
let quiz=[],index=0,answers=[];
const el=id=>document.getElementById(id);
const show=id=>el(id).classList.remove('hidden');
const hide=id=>el(id).classList.add('hidden');
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function escapeHtml(text){return String(text).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function selectedCount(){const raw=el('countSelect').value;return raw==='all'?BANK.length:Math.min(Number(raw),BANK.length);}
function makeQuiz(){const n=selectedCount();quiz=shuffle(BANK).slice(0,n).map(q=>({...q,options:shuffle(q.options)}));answers=Array(quiz.length).fill(null);index=0;hide('home');hide('summary');show('quiz');render();window.scrollTo({top:0,behavior:'smooth'});}
function resetQuiz(){answers=Array(quiz.length).fill(null);index=0;hide('summary');show('quiz');render();window.scrollTo({top:0,behavior:'smooth'});}
function finishPractice(){hide('quiz');hide('summary');show('home');el('bankInfo').textContent=`Ngân hàng có ${BANK.length} câu. Lần tới mở lên bấm Bắt đầu ôn để tạo đề mới.`;window.scrollTo({top:0,behavior:'smooth'});}
function score(){let right=0,wrong=0;answers.forEach((a,i)=>{if(a===null)return;quiz[i].options[a].correct?right++:wrong++;});return{right,wrong};}
function render(){const q=quiz[index];const s=score();el('bankInfo').textContent=`Đề ${quiz.length} câu, trộn ngẫu nhiên từ ${BANK.length} câu trong đề cương.`;el('bar').style.width=`${((index+1)/quiz.length)*100}%`;el('qIndex').textContent=`${index+1}/${quiz.length}`;el('rightPill').textContent=`✓ ${s.right}`;el('wrongPill').textContent=`× ${s.wrong}`;el('questionNo').textContent=`Câu hỏi ${index+1}`;el('stem').textContent=q.question;const chosen=answers[index];const checked=chosen!==null;const box=el('options');box.innerHTML='';q.options.forEach((op,i)=>{const b=document.createElement('button');b.className='option';if(chosen===i)b.classList.add('selected');if(checked&&op.correct)b.classList.add('correct');if(checked&&chosen===i&&!op.correct)b.classList.add('wrong');b.innerHTML=`<span class="letter">${letters[i]}.</span><span>${escapeHtml(op.text)}</span><span class="mark">${checked?(op.correct?'✓':(chosen===i?'×':'')):''}</span>`;if(checked){const ex=document.createElement('div');ex.className='explain';ex.textContent=op.correct?q.explanation:(chosen===i?`Chưa đúng. Đối chiếu với đề cương: ${q.explanation}`:'');if(ex.textContent)b.appendChild(ex);}b.onclick=()=>{if(answers[index]===null){answers[index]=i;render();}};box.appendChild(b);});el('prevBtn').disabled=index===0;el('nextBtn').textContent=index===quiz.length-1?'Chấm kết quả':'Tiếp theo';}
function showSummary(){const s=score();const skipped=answers.filter(a=>a===null).length;const pct=Math.round((s.right/quiz.length)*100);hide('quiz');const rows=quiz.map((q,i)=>{const a=answers[i];const correct=q.options.find(o=>o.correct);const your=a===null?'Bỏ qua':q.options[a].text;const ok=a!==null&&q.options[a].correct;return `<div class="reviewItem ${ok?'ok':'no'}"><b>Câu ${i+1}: ${escapeHtml(q.question)}</b><div>Bạn chọn: ${escapeHtml(your)}</div><div>Đáp án đúng: ${escapeHtml(correct.text)}</div><div>${escapeHtml(q.explanation)}</div></div>`}).join('');el('summary').innerHTML=`<h2>Tuyệt vời! Bạn đã hoàn thành bài kiểm tra.</h2><div class="stats"><div class="stat"><span>Điểm</span><strong>${s.right}/${quiz.length}</strong><div>Không chính xác: ${s.wrong}<br>Bỏ qua: ${skipped}</div></div><div class="stat"><span>Độ chính xác</span><strong>${pct}%</strong></div></div><div class="nav"><button class="btn" onclick="resetQuiz()">Làm lại đề này</button><button class="btn blue" onclick="makeQuiz()">Đề khác</button><button class="btn ghost" onclick="finishPractice()">Kết thúc ôn</button></div><h2>Đối chiếu đáp án</h2><div class="reviewList">${rows}</div>`;show('summary');window.scrollTo({top:0,behavior:'smooth'});}
el('nextBtn').onclick=()=>{if(index<quiz.length-1){index++;render();window.scrollTo({top:0,behavior:'smooth'});}else showSummary();};
el('prevBtn').onclick=()=>{if(index>0){index--;render();window.scrollTo({top:0,behavior:'smooth'});}};
el('newBtn').onclick=makeQuiz;el('resetBtn').onclick=()=>quiz.length?resetQuiz():makeQuiz();el('startBtn').onclick=makeQuiz;
el('modeBtn').onclick=()=>{document.documentElement.classList.toggle('dark');el('modeBtn').textContent=document.documentElement.classList.contains('dark')?'Chế độ sáng':'Chế độ tối';};
async function boot(){try{const res=await fetch('questions.json',{cache:'no-store'});BANK=await res.json();el('bankInfo').textContent=`Ngân hàng có ${BANK.length} câu từ đề cương.`;if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}}catch(e){el('bankInfo').textContent='Không tải được dữ liệu câu hỏi. Hãy mở qua máy chủ web hoặc bản đã host.';console.error(e);}}
boot();